fragment PageParts on Page {
  __typename
  title
  body
}

fragment PostParts on Post {
  __typename
  title
  date
  category
  image
  body
}

fragment SettingsParts on Settings {
  __typename
  siteName
  tagline
  description
  facebookUrl
  instagramUrl
  contactEmail
}
